src/AbstractFFTs.jl
We need to import the things from Base on versions where we don't define them in the package. These extra things aren't exported here but are imported by other packages.
=> Import more things from Base on older Julia

src/definitions.jl, test/runtests.jl
`Int(x)` does no longer wrap `convert(Int, x)::Int`, so the type
assertion has be added manually to ensure inferability. Fixes
JuliaMath/FFTW.jl#57.
=> Add a typeassert in `normalization`

.gitignore, .travis.yml, Project.toml, REQUIRE, docs/Project.toml, docs/make.jl, docs/src/index.md, src/AbstractFFTs.jl, src/definitions.jl, test/runtests.jl
This drops support for Julia versions prior to 1.0, allowing us to simplify version checking logic and drop the dependency on Compat.
This also updates the documentation setup.
=> Updates for Julia 1.0+

src/definitions.jl
Expression in `unsafe_getindex` is simpler and more understandable. However `@code_native` produces the same code (on Linux, x64) so there is no resulting optimization.
=> Simplify expression

src/definitions.jl, test/runtests.jl
This was supposed to fix #36. Although in the end `@code_warntype fftshift(rand(ComplexF64,64,64))` shows no problems on the latest Julia (although it does print a bit less with this PR) and isn't fixed on Julia 1.0! 
It also adds a method for `copy(fftfreq(8))`, this previously gave an Array, whereas now it behaves like `copy(1:8)`. I think `collect(1:8)` or `Array(1:8)` are the ways to make an Array.
=> Use tuples in fftshift, and add copy method

src/definitions.jl
This PR updates the docstrings for `fftfreq` and `rfftfreq`, explicitly listing the frequencies returned and adding some examples.
=> Update docstrings for fftfreq and rfftfreq

src/definitions.jl, test/runtests.jl
The minimum and maximum for a `Frequencies` object may be computed without iteration.
on master:
```julia
julia> freqs = fftfreq(100, 1);
julia> @btime maximum($freqs)
451.650 ns (0 allocations: 0 bytes)
0.49
```
After this PR:
```julia
julia> @btime maximum($(Ref(freqs))[])
3.194 ns (0 allocations: 0 bytes)
0.49
```
It effectively uses the bounds from `fftshift`. The reason to avoid calling `fftshift` directly is that constructing the range is expensive, but computing the bounds is cheap.
=> Fast extrema computation for Frequencies

Project.toml, src/definitions.jl, test/runtests.jl
This is technically a breaking change because it returns the sizes as
tuples rather than vectors. Hence I've taken the liberty of bumping
the version number.
=> Improve inferrability

README.md, docs/src/implementations.md
See https://github.com/JuliaApproximation/FastTransforms.jl/pull/64.
=> Mention implementation in FastTransforms.jl

Project.toml, src/definitions.jl, test/runtests.jl
Before:
```
julia> import Unitful: mm
julia> using FFTW
julia> fftfreq(10, 1.0mm);
julia> minimum(f)
ERROR: DimensionError: 0.0 and 0.1 mm are not dimensionally compatible.
```
After:
```
julia> import Unitful: mm
julia> using FFTW
julia> fftfreq(10, 1.0mm);
julia> minimum(f)
-0.5mm
```
I didn't include a test, but if you are ok w/ including `Unitful` in test dependencies I can put that in.
=> Make minimum/maximum generic for Frequencies

.github/workflows/TagBot.yml
I noticed that the documentation for v1.0.0 (and following) wasn't deployed.
@pfitzseb found the problem: TagBot should be configured with the documenter key, as explained in the [Documenter.jl docs](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions).
The next tagged version should then have the docs deployed correctly.
Edit: this fixes #60
=> fix docs not deploying for tagged versions

src/AbstractFFTs.jl, src/definitions.jl, test/runtests.jl
Adds nonallocating versions of `fftshift` and `ifftshift` with the corresponding tests. Fixes #62
=> `fftshift!` and `ifftshift!`

Project.toml, README.md, docs/src/api.md, src/AbstractFFTs.jl, src/definitions.jl, test/runtests.jl
Currently, there is no official and consistent way for accessing the transformed region of a FFT plan. For many plans, `plan.region` works but e.g. it fails for `ScaledPlan`. This is problematic when one tries to write generic implementations, e.g., of derivatives (see, e.g., https://github.com/JuliaMath/FFTW.jl/issues/182).
This PR adds a function `region(p::Plan)` that can be used to access the region of a plan. It falls back to `p.region` but can be specialized, e.g., for `ScaledPlan`.
=> Add `region(::Plan)` for accessing transformed region

src/definitions.jl, test/testplans.jl
This PR fixes some incorrect caching logic in the test plans. The reason this escaped notice is because `ScaledPlan` uses `plan_inv` rather than `inv`. That has been changed too.
**(Old Description)**
There is no need to do the caching in `plan_inv` as it should be handled by `AbstractFFTs`. The current logic leads to the following error which is now fixed.
```
julia> using AbstractFFTs
[ Info: Precompiling AbstractFFTs [621f4979-c628-5d54-868e-fcf4e3e8185c]
julia> using AbstractFFTs: Plan
julia> include("test/testplans.jl")
julia> p = plan_fft(rand(3))
TestPlan{ComplexF64, 1}(1:1, (3,), #undef)
julia> inv(inv(p).p)
ERROR: TypeError: in typeassert, expected AbstractFFTs.ScaledPlan{ComplexF64, TestPlan{ComplexF64, 1}, ComplexF64}, got a value of type TestPlan{ComplexF64, 1}
Stacktrace:
[1] …
```
=> Correct inverse plan logic

src/definitions.jl
Now that the inner plans inside scaled plans automatically store a cache of the inverse, it seems unnecessary to store another cache outside in the scaled plan (https://github.com/JuliaMath/AbstractFFTs.jl/pull/69). This has the benefit that we can make `ScaledPlan` immutable, which can simplify the logic for differentiating w.r.t. the plan scale.
=> Immutable ScaledPlan

src/definitions.jl, test/runtests.jl, test/testplans.jl
Fixes a downstream issue in FFTW's tests caused by https://github.com/JuliaMath/AbstractFFTs.jl/pull/72
=> Support `plan_inv` for ScaledPlan's

.github/workflows/IntegrationTest.yml
In the same way as in ChainRules, SciML, Turing etc. In contrast to #75 this avoids a circular dependency and does not cause test errors for breaking releases.
=> Add downstream integration tests

.github/workflows/CI.yml, Project.toml, ext/AbstractFFTsChainRulesCoreExt.jl, src/AbstractFFTs.jl
Moving ChainRulesCore support to an extension will reduce load times for users on Julia >= 1.9 that do not load ChainRulesCore (directly or indirectly). Moreover, in contrast to Requires, the module will be precompiled if loaded. For users on Julia < 1.9 nothing will change and ChainRulesCore will be a regular dependency.
The new extension feature is explained in more detail here: https://pkgdocs.julialang.org/dev/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)
=> Make ChainRulesCore a weak dependency on Julia >= 1.9

ext/AbstractFFTsChainRulesCoreExt.jl
It always defines an `Array` which can fail on the GPU. This forces it to be the right type. One could also use `adapt` here, but since the element type promotion would have to occur anyways in the subsequent broadcast it seems you might as well convert all at once.
=> For conversion of scale vector in adjoint

Project.toml, src/AbstractFFTs.jl, test/runtests.jl
I'd suggest reverting this PR: https://github.com/JuliaMath/AbstractFFTs.jl/pull/107#issuecomment-1608470656
=> Revert "put chainrules core in a requires block, rm it from deps"

Project.toml, README.md, docs/Project.toml, docs/src/api.md, docs/src/implementations.md, ext/AbstractFFTsChainRulesCoreExt.jl, src/chainrules.jl, src/definitions.jl, test/runtests.jl, test/testplans.jl
An `rfft` can be written as `PF` where `F` is the `n x n` Fourier transform and `P` is a projection operator that removes the redundant information due to conjuagate symmetry. Because of `P`, the adjoint of real FFTs (real inverse FFTs) require a special scaling before (after) applying the backwards transformation. As discussed in https://github.com/JuliaMath/AbstractFFTs.jl/issues/63 this motivates supporting the  `Base.adjoint` operation for plans to simplify the writing of backward rules for AD.
The following functions must be implemented by backends in order for `output_size(p::Plan)` and `AdjointPlan` to work:
- `projection_style(p::Plan)` which can either be `:none`, `:real`, or `:real_inv`.
- `irfft_dim(p::Plan)`, only for those plans with `:real_inv` projection style, which gives …
=> Chain rules for FFT plans via AdjointPlans

docs/src/api.md, docs/src/implementations.md, src/definitions.jl, test/testplans.jl
This PR makes the projection styles subtypes of an abstract type. This is so that new projection styles can be added in downstream packages. In FFTW.jl, we are defining projection styles for DCT and FFTW.R2R transforms in https://github.com/JuliaMath/FFTW.jl/pull/249.
@gaurav-arya can you add a few lines of documentation for the different ProjectionStyles? For example,
~I fear that the names are slightly confusing. Specifically, `NoProjectionStyle` made it seem like it would be applicable to unitary transforms. But it looks like `NoProjectionStyle` is applicable to `fft/bfft`.~
=> Rename ProjectionStyle -> AdjointStyle, _mul -> AdjointMul, and improve docs

ext/AbstractFFTsTestExt.jl
Possible test to add to https://github.com/JuliaMath/AbstractFFTs.jl/pull/116
Note that this PR is to #116's branch (i.e. basically a code suggestion, but needed to do it this way since the test file was previously unchanged)
=> Test view inputs in interface tests

ext/AbstractFFTsChainRulesCoreExt.jl, ext/AbstractFFTsTestExt.jl, src/definitions.jl
Alternative to https://github.com/JuliaMath/AbstractFFTs.jl/pull/114 that avoids the computation of the array of scaling factors completely.
Tested locally with regular arrays and static arrays. Using `broadcast` instead of `map` (potentially including `d` etc. as broadcasted arguments) would return `SizedArray`s instead of `StaticArray`s for `SArray` inputs, hence I went with `map` instead.
Has to be tested with Zygote and CUDA as well (for the latter it might be useful to set up GPU tests with buildkite and for the former downstream tests with Zygote, limited to FFTs, would be useful).
Edit: Tests of Zygote#master pass locally with this PR.
=> Remove arrays of scaling factors

docs/src/api.md, docs/src/implementations.md, ext/AbstractFFTsTestExt.jl, src/definitions.jl, test/runtests.jl
This PR resolves #110. After some thinking I realized that the right way to do this should be to actually call `inv(p)` in the formation of the adjoint plan. This makes `adjoint(p)` work the same way as `inv(p)`, in that caching occurs in the plan formation rather than plan application.
As a consequence, I realized that  `output_size` should not actually be job of an adjoint style. TPlan implementers are actually already required to manually figure out output size for their plan when implementing `size(plan_inv(p))`, and hence it didn't actually make sense to have the adjoint style trait provide this. If we want to make to make the output size available for free without forming the inverse plan, that's a separate line of work (that could also simplify the lives of the original plan …
=> Eagerly invert plan on formation of AdjointPlan: correct eltype and remove output_size

src/TestUtils.jl
Previously, the use of `AbstractFFTs` within the `get_extension` call threw an error within the error hint handler.
=> Fix bug with TestUtils error hint handler

src/definitions.jl, test/TestPlans.jl, test/runtests.jl
@devmotion although I was unable to reproduce your concern in https://github.com/JuliaMath/AbstractFFTs.jl/pull/113#discussion_r1315782241, I've tried to make some tweaks to safeguard against any possible type issues in adjoint plans, and also added a test of the promotion behaviour.
Please let me know if you have any remaining concerns -- since this is still blocking release I would also be happy to revert the optimization implemented in #113 if you have concerns about the design that aren't easy to address.
=> Increasing robustness of adjoint plan optimizations

src/definitions.jl, test/runtests.jl
This PR specializes `show` for `Frequencies`. It's a workaround for https://github.com/JuliaLang/julia/issues/39963, and in general this makes the output more readable while displaying frequencies obtained from `fftfreq` and `rfftfreq`.
On master
```julia
julia> f = fftfreq(5, 0.3)
5-element Frequencies{Float64}:
0.0
0.06
0.12
-0.12
-0.06
julia> show(f)
[0.0, 0.06, 0.12, -0.12, -0.06]
julia> f = rfftfreq(5, 0.3)
3-element Frequencies{Float64}:
0.0
0.06
0.12
julia> show(f)
[0.0, 0.06, 0.12]
```
After this PR:
```julia
julia> f = fftfreq(5, 0.3)
5-element Frequencies{Float64}:
0.0
0.06
0.12
-0.12
-0.06
julia> show(f)
[0:2; -2:-1]*0.06
julia> f = rfftfreq(5, 0.3)
3-element Frequencies{Float64}:
0.0
0.06
0.12
julia> show(f)
[0:2;]*0.06
```
As a consequence:
on master
```julia
julia> g() = …
```
=> Compact show for Frequencies

src/definitions.jl, test/runtests.jl
Normalization is defined as `1/prod(dimensions)`, which should be well-defined for an empty `dimensions` (in which case the prod evaluates to `1`). This PR gets around the following error:
```julia
julia> AbstractFFTs.normalization(zeros(), 1:0)
ERROR: MethodError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
```
and the following runtime dispatch that arises from the error:
```julia
julia> using JET
julia> @report_opt AbstractFFTs.normalization(rand(4), 1:1)
═════ 1 possible error found ═════
┌ @ /home/jishnu/Dropbox/JuliaPackages/AbstractFFTs.jl/src/definitions.jl:275 AbstractFFTs.normalization(AbstractFFTs.real(AbstractFFTs.eltype(X)), AbstractFFTs.size(X), region)
│┌ @ /home/jishnu/Dropbox/JuliaPackages/AbstractFFTs.jl/src/definitions.jl:27 …
```
=> pass init to prod in normalization

.github/workflows/Documenter.yml
xref: https://github.com/JuliaCI/PkgTemplates.jl/blob/c3545770ce44b053201b93871feb39bd06566709/templates/github/workflows/CI.yml
=> ci: fix doc deploy

.github/workflows/Documenter.yml, docs/Project.toml, src/definitions.jl
=> fix(docs): Update Documenter setup
